---
- name: ranger-dns
  box: centos/7
  ip: 10.100.0.2
  mem: 1024
  cpu: 2
- name: ranger
  box: centos/7
  ip: 10.100.0.3
  mem: 8092
  cpu: 2
- name: ranger-nn
  box: centos/7
  ip: 10.100.0.4
  mem: 8092
  cpu: 2
- name: ranger-dn1
  box: centos/7
  ip: 10.100.0.5
  mem: 8092
  cpu: 2
- name: ranger-dn2
  box: centos/7
  ip: 10.100.0.6
  mem: 8092
  cpu: 2
- name: ranger-dn3
  box: centos/7
  ip: 10.100.0.7
  mem: 8092
  cpu: 2
- name: ranger-hive
  box: centos/7
  ip: 10.100.0.8
  mem: 8092
  cpu: 2
