---
- name: masters
  box: centos/7
  ip: 10.0.0.2
  mem: 8096
  cpu: 2
- name: tablet-server01
  box: centos/7
  ip: 10.0.0.3
  mem: 8096
  cpu: 2
  aditional_disk:
    - 10G
    - 10G
- name: tablet-server02
  box: centos/7
  ip: 10.0.0.4
  mem: 8096
  cpu: 2
  aditional_disk:
    - 10G
    - 10G
- name: tablet-server03
  box: centos/7
  ip: 10.0.0.5
  mem: 8096
  cpu: 2
  aditional_disk:
    - 10G
    - 10G
- name: sources
  box: centos/7
  ip: 10.0.0.6
  mem: 4096
  cpu: 2
- name: dns
  box: centos/7
  ip: 10.0.0.7
  mem: 2048
  cpu: 2
